//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Dependency/Input/GameAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameAction"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""bd33d136-863a-4ca4-a600-b2ca3eabcced"",
            ""actions"": [
                {
                    ""name"": ""Gather"",
                    ""type"": ""Button"",
                    ""id"": ""07547acb-fea7-4f44-85e6-64847dc755bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shop"",
                    ""type"": ""Button"",
                    ""id"": ""31513b56-4187-4a06-8c9f-cca6d03a3bc2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill1"",
                    ""type"": ""Button"",
                    ""id"": ""93fec820-da9d-42ef-b355-1735436818c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill2"",
                    ""type"": ""Button"",
                    ""id"": ""c315ae02-1c5c-40d8-bcd2-9857757f89eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill3"",
                    ""type"": ""Button"",
                    ""id"": ""ab72512d-976c-4904-8094-b31a1b184dc4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill4"",
                    ""type"": ""Button"",
                    ""id"": ""3a750a06-040a-48db-9962-9f2e94a59ade"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""e6ff59ba-4679-4eed-b49c-1efa884351ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press,Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""e2ff3fae-7b18-49eb-a5f7-f2deabe0d179"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lock"",
                    ""type"": ""Button"",
                    ""id"": ""13713f38-f964-4a38-9f08-0904edde2210"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapen1"",
                    ""type"": ""Button"",
                    ""id"": ""b0469d75-f73c-49c3-960a-db0c41b3a2c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapen2"",
                    ""type"": ""Button"",
                    ""id"": ""ba7c68fc-7314-435a-9122-ee9bef8854b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapen3"",
                    ""type"": ""Button"",
                    ""id"": ""c7552172-9c3b-4dde-9934-c406340841ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapen4"",
                    ""type"": ""Button"",
                    ""id"": ""12a6c984-f40a-4d7c-94bb-34407a12cba4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapen5"",
                    ""type"": ""Button"",
                    ""id"": ""96dca76f-3c5d-44f7-a3b7-962e81f9b129"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapen6"",
                    ""type"": ""Button"",
                    ""id"": ""668f6e6f-bc6c-4e87-a96c-55cc8440fe44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapen7"",
                    ""type"": ""Button"",
                    ""id"": ""76a11a98-e016-47db-8c77-4448494e29b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapen8"",
                    ""type"": ""Button"",
                    ""id"": ""c78616d2-8895-4a80-9edc-1f608e1875d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapen9"",
                    ""type"": ""Button"",
                    ""id"": ""90390c1a-6a8d-4a15-aba7-653718d2f15a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenSwitchAuto1"",
                    ""type"": ""Button"",
                    ""id"": ""b25541a8-4ca8-40a4-99f0-00f14b024715"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenSwitchAuto2"",
                    ""type"": ""Button"",
                    ""id"": ""e2de43fa-edaf-4c2d-9be6-0ecc214bbb57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenSwitchAuto3"",
                    ""type"": ""Button"",
                    ""id"": ""67577f9c-4e64-490e-8795-5e7d8a337dd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenSwitchAuto4"",
                    ""type"": ""Button"",
                    ""id"": ""93dcaeda-f72e-4315-8aa5-a961611c86c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenSwitchAuto5"",
                    ""type"": ""Button"",
                    ""id"": ""243551e2-de4f-4187-a26c-32899ce60052"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenSwitchAuto6"",
                    ""type"": ""Button"",
                    ""id"": ""2b01f41f-cbaf-4452-be86-b3472677f5be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenSwitchAuto7"",
                    ""type"": ""Button"",
                    ""id"": ""c99e24a6-5b92-4246-8d58-7b5b838195ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenSwitchAuto8"",
                    ""type"": ""Button"",
                    ""id"": ""2f81bcc0-340c-4250-a90a-364ba71e2a93"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeapenSwitchAuto9"",
                    ""type"": ""Button"",
                    ""id"": ""b17663ec-8ea6-4d82-9af4-1c29ba3bfe7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Config"",
                    ""type"": ""Button"",
                    ""id"": ""205409f0-c44d-4703-945d-efd2353aec74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""c831ee5b-f951-4d49-aa93-9c707a44dbe2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a3f897a6-58d8-4256-a90c-40292669aab0"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gather"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecb7a36e-6164-44fa-a414-2b84dd232722"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c77d9253-a40c-4a07-ae88-38f8d30ab4a3"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c82d4920-605d-4cca-be75-5c0824d69bc9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bcfd165-291d-4e1d-9261-117f7f728df6"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc89ed44-a795-4233-92d5-c8785bc6d02c"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""792b3716-09ff-46a3-861a-87497b799817"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce30eae1-8bb2-48c3-8fe1-5b65df39cd83"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3c85e43-1562-455b-b40f-e78f03c79ab7"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62738382-c0da-4cec-b2ce-e42fbdbe94f1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapen1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb78ef97-f825-4d05-9fc5-812c82a6d9e5"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapen2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2afe3a4-03ee-4602-a0ea-029a8d46ea03"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapen3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cea3b7d7-001c-4509-8f47-94b1b116ddb2"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapen4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf654963-9829-405f-8b3d-bd61f4ff1be9"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapen5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3226614d-3422-48cc-9687-1a8b8d0c0aa6"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapen6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efdafc98-a1ae-4e99-8ee1-2780932f698f"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapen7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e8ccf77-0fcb-4219-9d05-d5bf6bd108b2"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapen8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31829973-5142-46fa-987e-6146fa974c1f"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapen9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""e82198f0-baa5-4e9f-b359-d1c1d6574fe1"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""2eb1fe96-0363-4597-9d31-0818276cdcd9"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""988eb8a6-6a12-47e6-8364-11902e476111"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""bb6cf1c1-de2b-4ccd-8eee-acecfe27aeae"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""fe1e4e81-5d40-46be-a559-2acb2de4031c"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""b0b27df7-081b-4dc0-b013-e82bef0510b0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""6ca86244-cb7f-4f71-adaf-2990be7fa583"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""de17e036-ca4c-43ad-b915-1e60000e8789"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""a7a5fefd-17e9-4a15-a671-fa2c79498fe3"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""f5dfb43a-459f-40b9-875c-a5380b6ee487"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""86a1e514-1a02-4e9d-9ad4-c7b8dccecf0a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""c198f89a-9e32-443c-b057-1958f0f8cefe"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""2b8c4e86-659a-4154-834d-b11494bb4120"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto5"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""321538c5-aeab-4f44-bf94-7ae83da7cb12"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""51427e0a-a7cc-4f97-923e-60faf532bed1"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""068f160a-1290-4a9b-b5b3-04203ae997e5"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto6"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""4f8bdb89-9b8c-450a-a95e-908d20ff5ab0"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""8880977d-940b-4218-9424-984f2f3dca36"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""61443fd4-ace6-4baa-9193-7b4c9749cf1e"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto7"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""be509fa5-a842-47bd-b2ec-5720d586b468"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""f6856dfb-058c-4735-aa53-674fa4e36e5b"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""07135293-b00d-415f-b70f-bc62221f4436"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto8"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""f83052e5-f18b-46ec-a188-9982af01ef90"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""85d9b96a-2d8e-43f8-b4a8-aacd72762d16"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""85666128-ea8d-43f2-b6df-4706c52f01fd"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto9"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""76c533f2-357d-4c68-8919-8ff5acd3e8ea"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""5ffb7a1e-7678-4859-bf7d-925bd6b6a400"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeapenSwitchAuto9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a1612271-5336-40a3-b3a8-d34ab7f5c594"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Config"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6073f88b-d245-4bc1-b83b-f600c3017f52"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_Gather = m_Game.FindAction("Gather", throwIfNotFound: true);
        m_Game_Shop = m_Game.FindAction("Shop", throwIfNotFound: true);
        m_Game_Skill1 = m_Game.FindAction("Skill1", throwIfNotFound: true);
        m_Game_Skill2 = m_Game.FindAction("Skill2", throwIfNotFound: true);
        m_Game_Skill3 = m_Game.FindAction("Skill3", throwIfNotFound: true);
        m_Game_Skill4 = m_Game.FindAction("Skill4", throwIfNotFound: true);
        m_Game_Fire = m_Game.FindAction("Fire", throwIfNotFound: true);
        m_Game_Move = m_Game.FindAction("Move", throwIfNotFound: true);
        m_Game_Lock = m_Game.FindAction("Lock", throwIfNotFound: true);
        m_Game_Weapen1 = m_Game.FindAction("Weapen1", throwIfNotFound: true);
        m_Game_Weapen2 = m_Game.FindAction("Weapen2", throwIfNotFound: true);
        m_Game_Weapen3 = m_Game.FindAction("Weapen3", throwIfNotFound: true);
        m_Game_Weapen4 = m_Game.FindAction("Weapen4", throwIfNotFound: true);
        m_Game_Weapen5 = m_Game.FindAction("Weapen5", throwIfNotFound: true);
        m_Game_Weapen6 = m_Game.FindAction("Weapen6", throwIfNotFound: true);
        m_Game_Weapen7 = m_Game.FindAction("Weapen7", throwIfNotFound: true);
        m_Game_Weapen8 = m_Game.FindAction("Weapen8", throwIfNotFound: true);
        m_Game_Weapen9 = m_Game.FindAction("Weapen9", throwIfNotFound: true);
        m_Game_WeapenSwitchAuto1 = m_Game.FindAction("WeapenSwitchAuto1", throwIfNotFound: true);
        m_Game_WeapenSwitchAuto2 = m_Game.FindAction("WeapenSwitchAuto2", throwIfNotFound: true);
        m_Game_WeapenSwitchAuto3 = m_Game.FindAction("WeapenSwitchAuto3", throwIfNotFound: true);
        m_Game_WeapenSwitchAuto4 = m_Game.FindAction("WeapenSwitchAuto4", throwIfNotFound: true);
        m_Game_WeapenSwitchAuto5 = m_Game.FindAction("WeapenSwitchAuto5", throwIfNotFound: true);
        m_Game_WeapenSwitchAuto6 = m_Game.FindAction("WeapenSwitchAuto6", throwIfNotFound: true);
        m_Game_WeapenSwitchAuto7 = m_Game.FindAction("WeapenSwitchAuto7", throwIfNotFound: true);
        m_Game_WeapenSwitchAuto8 = m_Game.FindAction("WeapenSwitchAuto8", throwIfNotFound: true);
        m_Game_WeapenSwitchAuto9 = m_Game.FindAction("WeapenSwitchAuto9", throwIfNotFound: true);
        m_Game_Config = m_Game.FindAction("Config", throwIfNotFound: true);
        m_Game_Exit = m_Game.FindAction("Exit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private List<IGameActions> m_GameActionsCallbackInterfaces = new List<IGameActions>();
    private readonly InputAction m_Game_Gather;
    private readonly InputAction m_Game_Shop;
    private readonly InputAction m_Game_Skill1;
    private readonly InputAction m_Game_Skill2;
    private readonly InputAction m_Game_Skill3;
    private readonly InputAction m_Game_Skill4;
    private readonly InputAction m_Game_Fire;
    private readonly InputAction m_Game_Move;
    private readonly InputAction m_Game_Lock;
    private readonly InputAction m_Game_Weapen1;
    private readonly InputAction m_Game_Weapen2;
    private readonly InputAction m_Game_Weapen3;
    private readonly InputAction m_Game_Weapen4;
    private readonly InputAction m_Game_Weapen5;
    private readonly InputAction m_Game_Weapen6;
    private readonly InputAction m_Game_Weapen7;
    private readonly InputAction m_Game_Weapen8;
    private readonly InputAction m_Game_Weapen9;
    private readonly InputAction m_Game_WeapenSwitchAuto1;
    private readonly InputAction m_Game_WeapenSwitchAuto2;
    private readonly InputAction m_Game_WeapenSwitchAuto3;
    private readonly InputAction m_Game_WeapenSwitchAuto4;
    private readonly InputAction m_Game_WeapenSwitchAuto5;
    private readonly InputAction m_Game_WeapenSwitchAuto6;
    private readonly InputAction m_Game_WeapenSwitchAuto7;
    private readonly InputAction m_Game_WeapenSwitchAuto8;
    private readonly InputAction m_Game_WeapenSwitchAuto9;
    private readonly InputAction m_Game_Config;
    private readonly InputAction m_Game_Exit;
    public struct GameActions
    {
        private @GameAction m_Wrapper;
        public GameActions(@GameAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Gather => m_Wrapper.m_Game_Gather;
        public InputAction @Shop => m_Wrapper.m_Game_Shop;
        public InputAction @Skill1 => m_Wrapper.m_Game_Skill1;
        public InputAction @Skill2 => m_Wrapper.m_Game_Skill2;
        public InputAction @Skill3 => m_Wrapper.m_Game_Skill3;
        public InputAction @Skill4 => m_Wrapper.m_Game_Skill4;
        public InputAction @Fire => m_Wrapper.m_Game_Fire;
        public InputAction @Move => m_Wrapper.m_Game_Move;
        public InputAction @Lock => m_Wrapper.m_Game_Lock;
        public InputAction @Weapen1 => m_Wrapper.m_Game_Weapen1;
        public InputAction @Weapen2 => m_Wrapper.m_Game_Weapen2;
        public InputAction @Weapen3 => m_Wrapper.m_Game_Weapen3;
        public InputAction @Weapen4 => m_Wrapper.m_Game_Weapen4;
        public InputAction @Weapen5 => m_Wrapper.m_Game_Weapen5;
        public InputAction @Weapen6 => m_Wrapper.m_Game_Weapen6;
        public InputAction @Weapen7 => m_Wrapper.m_Game_Weapen7;
        public InputAction @Weapen8 => m_Wrapper.m_Game_Weapen8;
        public InputAction @Weapen9 => m_Wrapper.m_Game_Weapen9;
        public InputAction @WeapenSwitchAuto1 => m_Wrapper.m_Game_WeapenSwitchAuto1;
        public InputAction @WeapenSwitchAuto2 => m_Wrapper.m_Game_WeapenSwitchAuto2;
        public InputAction @WeapenSwitchAuto3 => m_Wrapper.m_Game_WeapenSwitchAuto3;
        public InputAction @WeapenSwitchAuto4 => m_Wrapper.m_Game_WeapenSwitchAuto4;
        public InputAction @WeapenSwitchAuto5 => m_Wrapper.m_Game_WeapenSwitchAuto5;
        public InputAction @WeapenSwitchAuto6 => m_Wrapper.m_Game_WeapenSwitchAuto6;
        public InputAction @WeapenSwitchAuto7 => m_Wrapper.m_Game_WeapenSwitchAuto7;
        public InputAction @WeapenSwitchAuto8 => m_Wrapper.m_Game_WeapenSwitchAuto8;
        public InputAction @WeapenSwitchAuto9 => m_Wrapper.m_Game_WeapenSwitchAuto9;
        public InputAction @Config => m_Wrapper.m_Game_Config;
        public InputAction @Exit => m_Wrapper.m_Game_Exit;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void AddCallbacks(IGameActions instance)
        {
            if (instance == null || m_Wrapper.m_GameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameActionsCallbackInterfaces.Add(instance);
            @Gather.started += instance.OnGather;
            @Gather.performed += instance.OnGather;
            @Gather.canceled += instance.OnGather;
            @Shop.started += instance.OnShop;
            @Shop.performed += instance.OnShop;
            @Shop.canceled += instance.OnShop;
            @Skill1.started += instance.OnSkill1;
            @Skill1.performed += instance.OnSkill1;
            @Skill1.canceled += instance.OnSkill1;
            @Skill2.started += instance.OnSkill2;
            @Skill2.performed += instance.OnSkill2;
            @Skill2.canceled += instance.OnSkill2;
            @Skill3.started += instance.OnSkill3;
            @Skill3.performed += instance.OnSkill3;
            @Skill3.canceled += instance.OnSkill3;
            @Skill4.started += instance.OnSkill4;
            @Skill4.performed += instance.OnSkill4;
            @Skill4.canceled += instance.OnSkill4;
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Lock.started += instance.OnLock;
            @Lock.performed += instance.OnLock;
            @Lock.canceled += instance.OnLock;
            @Weapen1.started += instance.OnWeapen1;
            @Weapen1.performed += instance.OnWeapen1;
            @Weapen1.canceled += instance.OnWeapen1;
            @Weapen2.started += instance.OnWeapen2;
            @Weapen2.performed += instance.OnWeapen2;
            @Weapen2.canceled += instance.OnWeapen2;
            @Weapen3.started += instance.OnWeapen3;
            @Weapen3.performed += instance.OnWeapen3;
            @Weapen3.canceled += instance.OnWeapen3;
            @Weapen4.started += instance.OnWeapen4;
            @Weapen4.performed += instance.OnWeapen4;
            @Weapen4.canceled += instance.OnWeapen4;
            @Weapen5.started += instance.OnWeapen5;
            @Weapen5.performed += instance.OnWeapen5;
            @Weapen5.canceled += instance.OnWeapen5;
            @Weapen6.started += instance.OnWeapen6;
            @Weapen6.performed += instance.OnWeapen6;
            @Weapen6.canceled += instance.OnWeapen6;
            @Weapen7.started += instance.OnWeapen7;
            @Weapen7.performed += instance.OnWeapen7;
            @Weapen7.canceled += instance.OnWeapen7;
            @Weapen8.started += instance.OnWeapen8;
            @Weapen8.performed += instance.OnWeapen8;
            @Weapen8.canceled += instance.OnWeapen8;
            @Weapen9.started += instance.OnWeapen9;
            @Weapen9.performed += instance.OnWeapen9;
            @Weapen9.canceled += instance.OnWeapen9;
            @WeapenSwitchAuto1.started += instance.OnWeapenSwitchAuto1;
            @WeapenSwitchAuto1.performed += instance.OnWeapenSwitchAuto1;
            @WeapenSwitchAuto1.canceled += instance.OnWeapenSwitchAuto1;
            @WeapenSwitchAuto2.started += instance.OnWeapenSwitchAuto2;
            @WeapenSwitchAuto2.performed += instance.OnWeapenSwitchAuto2;
            @WeapenSwitchAuto2.canceled += instance.OnWeapenSwitchAuto2;
            @WeapenSwitchAuto3.started += instance.OnWeapenSwitchAuto3;
            @WeapenSwitchAuto3.performed += instance.OnWeapenSwitchAuto3;
            @WeapenSwitchAuto3.canceled += instance.OnWeapenSwitchAuto3;
            @WeapenSwitchAuto4.started += instance.OnWeapenSwitchAuto4;
            @WeapenSwitchAuto4.performed += instance.OnWeapenSwitchAuto4;
            @WeapenSwitchAuto4.canceled += instance.OnWeapenSwitchAuto4;
            @WeapenSwitchAuto5.started += instance.OnWeapenSwitchAuto5;
            @WeapenSwitchAuto5.performed += instance.OnWeapenSwitchAuto5;
            @WeapenSwitchAuto5.canceled += instance.OnWeapenSwitchAuto5;
            @WeapenSwitchAuto6.started += instance.OnWeapenSwitchAuto6;
            @WeapenSwitchAuto6.performed += instance.OnWeapenSwitchAuto6;
            @WeapenSwitchAuto6.canceled += instance.OnWeapenSwitchAuto6;
            @WeapenSwitchAuto7.started += instance.OnWeapenSwitchAuto7;
            @WeapenSwitchAuto7.performed += instance.OnWeapenSwitchAuto7;
            @WeapenSwitchAuto7.canceled += instance.OnWeapenSwitchAuto7;
            @WeapenSwitchAuto8.started += instance.OnWeapenSwitchAuto8;
            @WeapenSwitchAuto8.performed += instance.OnWeapenSwitchAuto8;
            @WeapenSwitchAuto8.canceled += instance.OnWeapenSwitchAuto8;
            @WeapenSwitchAuto9.started += instance.OnWeapenSwitchAuto9;
            @WeapenSwitchAuto9.performed += instance.OnWeapenSwitchAuto9;
            @WeapenSwitchAuto9.canceled += instance.OnWeapenSwitchAuto9;
            @Config.started += instance.OnConfig;
            @Config.performed += instance.OnConfig;
            @Config.canceled += instance.OnConfig;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
        }

        private void UnregisterCallbacks(IGameActions instance)
        {
            @Gather.started -= instance.OnGather;
            @Gather.performed -= instance.OnGather;
            @Gather.canceled -= instance.OnGather;
            @Shop.started -= instance.OnShop;
            @Shop.performed -= instance.OnShop;
            @Shop.canceled -= instance.OnShop;
            @Skill1.started -= instance.OnSkill1;
            @Skill1.performed -= instance.OnSkill1;
            @Skill1.canceled -= instance.OnSkill1;
            @Skill2.started -= instance.OnSkill2;
            @Skill2.performed -= instance.OnSkill2;
            @Skill2.canceled -= instance.OnSkill2;
            @Skill3.started -= instance.OnSkill3;
            @Skill3.performed -= instance.OnSkill3;
            @Skill3.canceled -= instance.OnSkill3;
            @Skill4.started -= instance.OnSkill4;
            @Skill4.performed -= instance.OnSkill4;
            @Skill4.canceled -= instance.OnSkill4;
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Lock.started -= instance.OnLock;
            @Lock.performed -= instance.OnLock;
            @Lock.canceled -= instance.OnLock;
            @Weapen1.started -= instance.OnWeapen1;
            @Weapen1.performed -= instance.OnWeapen1;
            @Weapen1.canceled -= instance.OnWeapen1;
            @Weapen2.started -= instance.OnWeapen2;
            @Weapen2.performed -= instance.OnWeapen2;
            @Weapen2.canceled -= instance.OnWeapen2;
            @Weapen3.started -= instance.OnWeapen3;
            @Weapen3.performed -= instance.OnWeapen3;
            @Weapen3.canceled -= instance.OnWeapen3;
            @Weapen4.started -= instance.OnWeapen4;
            @Weapen4.performed -= instance.OnWeapen4;
            @Weapen4.canceled -= instance.OnWeapen4;
            @Weapen5.started -= instance.OnWeapen5;
            @Weapen5.performed -= instance.OnWeapen5;
            @Weapen5.canceled -= instance.OnWeapen5;
            @Weapen6.started -= instance.OnWeapen6;
            @Weapen6.performed -= instance.OnWeapen6;
            @Weapen6.canceled -= instance.OnWeapen6;
            @Weapen7.started -= instance.OnWeapen7;
            @Weapen7.performed -= instance.OnWeapen7;
            @Weapen7.canceled -= instance.OnWeapen7;
            @Weapen8.started -= instance.OnWeapen8;
            @Weapen8.performed -= instance.OnWeapen8;
            @Weapen8.canceled -= instance.OnWeapen8;
            @Weapen9.started -= instance.OnWeapen9;
            @Weapen9.performed -= instance.OnWeapen9;
            @Weapen9.canceled -= instance.OnWeapen9;
            @WeapenSwitchAuto1.started -= instance.OnWeapenSwitchAuto1;
            @WeapenSwitchAuto1.performed -= instance.OnWeapenSwitchAuto1;
            @WeapenSwitchAuto1.canceled -= instance.OnWeapenSwitchAuto1;
            @WeapenSwitchAuto2.started -= instance.OnWeapenSwitchAuto2;
            @WeapenSwitchAuto2.performed -= instance.OnWeapenSwitchAuto2;
            @WeapenSwitchAuto2.canceled -= instance.OnWeapenSwitchAuto2;
            @WeapenSwitchAuto3.started -= instance.OnWeapenSwitchAuto3;
            @WeapenSwitchAuto3.performed -= instance.OnWeapenSwitchAuto3;
            @WeapenSwitchAuto3.canceled -= instance.OnWeapenSwitchAuto3;
            @WeapenSwitchAuto4.started -= instance.OnWeapenSwitchAuto4;
            @WeapenSwitchAuto4.performed -= instance.OnWeapenSwitchAuto4;
            @WeapenSwitchAuto4.canceled -= instance.OnWeapenSwitchAuto4;
            @WeapenSwitchAuto5.started -= instance.OnWeapenSwitchAuto5;
            @WeapenSwitchAuto5.performed -= instance.OnWeapenSwitchAuto5;
            @WeapenSwitchAuto5.canceled -= instance.OnWeapenSwitchAuto5;
            @WeapenSwitchAuto6.started -= instance.OnWeapenSwitchAuto6;
            @WeapenSwitchAuto6.performed -= instance.OnWeapenSwitchAuto6;
            @WeapenSwitchAuto6.canceled -= instance.OnWeapenSwitchAuto6;
            @WeapenSwitchAuto7.started -= instance.OnWeapenSwitchAuto7;
            @WeapenSwitchAuto7.performed -= instance.OnWeapenSwitchAuto7;
            @WeapenSwitchAuto7.canceled -= instance.OnWeapenSwitchAuto7;
            @WeapenSwitchAuto8.started -= instance.OnWeapenSwitchAuto8;
            @WeapenSwitchAuto8.performed -= instance.OnWeapenSwitchAuto8;
            @WeapenSwitchAuto8.canceled -= instance.OnWeapenSwitchAuto8;
            @WeapenSwitchAuto9.started -= instance.OnWeapenSwitchAuto9;
            @WeapenSwitchAuto9.performed -= instance.OnWeapenSwitchAuto9;
            @WeapenSwitchAuto9.canceled -= instance.OnWeapenSwitchAuto9;
            @Config.started -= instance.OnConfig;
            @Config.performed -= instance.OnConfig;
            @Config.canceled -= instance.OnConfig;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
        }

        public void RemoveCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameActions instance)
        {
            foreach (var item in m_Wrapper.m_GameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameActions @Game => new GameActions(this);
    public interface IGameActions
    {
        void OnGather(InputAction.CallbackContext context);
        void OnShop(InputAction.CallbackContext context);
        void OnSkill1(InputAction.CallbackContext context);
        void OnSkill2(InputAction.CallbackContext context);
        void OnSkill3(InputAction.CallbackContext context);
        void OnSkill4(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnLock(InputAction.CallbackContext context);
        void OnWeapen1(InputAction.CallbackContext context);
        void OnWeapen2(InputAction.CallbackContext context);
        void OnWeapen3(InputAction.CallbackContext context);
        void OnWeapen4(InputAction.CallbackContext context);
        void OnWeapen5(InputAction.CallbackContext context);
        void OnWeapen6(InputAction.CallbackContext context);
        void OnWeapen7(InputAction.CallbackContext context);
        void OnWeapen8(InputAction.CallbackContext context);
        void OnWeapen9(InputAction.CallbackContext context);
        void OnWeapenSwitchAuto1(InputAction.CallbackContext context);
        void OnWeapenSwitchAuto2(InputAction.CallbackContext context);
        void OnWeapenSwitchAuto3(InputAction.CallbackContext context);
        void OnWeapenSwitchAuto4(InputAction.CallbackContext context);
        void OnWeapenSwitchAuto5(InputAction.CallbackContext context);
        void OnWeapenSwitchAuto6(InputAction.CallbackContext context);
        void OnWeapenSwitchAuto7(InputAction.CallbackContext context);
        void OnWeapenSwitchAuto8(InputAction.CallbackContext context);
        void OnWeapenSwitchAuto9(InputAction.CallbackContext context);
        void OnConfig(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
    }
}
